# Generated by Django 4.0.1 on 2022-01-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1000)),
                ('is_leaf', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
    ]
