# Generated by Django 4.0.1 on 2022-01-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductVariations',
            fields=[
                ('product_v_id', models.AutoField(primary_key=True, serialize=False)),
                ('colour', models.TextField(max_length=1000)),
                ('product_size', models.TextField(max_length=1000)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('original_price', models.FloatField(default=1)),
                ('selling_price', models.FloatField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.product')),
            ],
            options={
                'db_table': 'Product_Variations',
            },
        ),
    ]
